/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import cliente.Cliente;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import misc.IP;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author gcs
 */
public class Conexion extends javax.swing.JPanel {
    
    private final String CONEXIONESRECIENTES = "IPr.txt";
    
    private BienvenidaFrame frame;
    private ArrayList<String> conexionesRecientes;
    
    /**
     * Creates new form Conexion
     */
    public Conexion(BienvenidaFrame frame) {
        initComponents();
        this.frame = frame;
        conexionesRecientes = new ArrayList();
        try {
            leerConexionesRecientes();
        } catch (IOException ex) {
            System.out.println("No se encontraron IP:puerto recientes");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        conexion_texto_ip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        conexion_texto_puerto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        conexion_textPanel_ippuerto = new javax.swing.JTextArea();
        conexion_boton_apagar = new javax.swing.JButton();
        conexion_boton_conectar = new javax.swing.JButton();
        conexion_boton_desconectar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        conexion_actualizar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(718, 568));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conectar a"));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("IP");

        conexion_texto_ip.setText("192.168.0.1");
        conexion_texto_ip.setToolTipText("IP servidor");
        conexion_texto_ip.setName(""); // NOI18N
        conexion_texto_ip.setPreferredSize(new java.awt.Dimension(130, 34));
        conexion_texto_ip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conexion_texto_ipFocusGained(evt);
            }
        });
        conexion_texto_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexion_texto_ipActionPerformed(evt);
            }
        });
        conexion_texto_ip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                conexion_texto_ipKeyPressed(evt);
            }
        });

        jLabel8.setText("Puerto");

        conexion_texto_puerto.setText("4040");
        conexion_texto_puerto.setToolTipText("puerto servidor");
        conexion_texto_puerto.setPreferredSize(new java.awt.Dimension(60, 34));
        conexion_texto_puerto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conexion_texto_puertoFocusGained(evt);
            }
        });
        conexion_texto_puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexion_texto_puertoActionPerformed(evt);
            }
        });
        conexion_texto_puerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                conexion_texto_puertoKeyPressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("IP:puerto recientes");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        conexion_textPanel_ippuerto.setEditable(false);
        conexion_textPanel_ippuerto.setBackground(new java.awt.Color(254, 254, 254));
        conexion_textPanel_ippuerto.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        conexion_textPanel_ippuerto.setTabSize(0);
        conexion_textPanel_ippuerto.setToolTipText("<ip>:<puerto>");
        jScrollPane2.setViewportView(conexion_textPanel_ippuerto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conexion_texto_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conexion_texto_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conexion_texto_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conexion_texto_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conexion_texto_ip.getAccessibleContext().setAccessibleName("IP servidor");
        conexion_texto_puerto.getAccessibleContext().setAccessibleName("");

        conexion_boton_apagar.setText("Desconectar y apagar");
        conexion_boton_apagar.setToolTipText("Desconectar del servidor y apagarlo");
        conexion_boton_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexion_boton_apagarActionPerformed(evt);
            }
        });

        conexion_boton_conectar.setText("Conectar");
        conexion_boton_conectar.setToolTipText("Conectar al servidor");
        conexion_boton_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexion_boton_conectarActionPerformed(evt);
            }
        });

        conexion_boton_desconectar.setText("Desconectar");
        conexion_boton_desconectar.setToolTipText("Desconectar del servidor y no apagarlo");
        conexion_boton_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexion_boton_desconectarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
        jLabel1.setText("CONEXIÓN");

        conexion_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_autorenew_black_24dp.png"))); // NOI18N
        conexion_actualizar.setToolTipText("Refrescar");
        conexion_actualizar.setPreferredSize(new java.awt.Dimension(36, 36));
        conexion_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexion_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(conexion_boton_conectar)
                            .addComponent(conexion_boton_desconectar)
                            .addComponent(conexion_boton_apagar)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conexion_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conexion_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(95, 95, 95)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(conexion_boton_conectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conexion_boton_desconectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conexion_boton_apagar)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void conexion_boton_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexion_boton_conectarActionPerformed
        // TODO add your handling code here:
   
        frame.setIpServer(conexion_texto_ip.getText());
        frame.setPuertoServer(conexion_texto_puerto.getText());
        frame.setCliente(new Cliente(frame.getIpServer(), Integer.parseInt(frame.getPuertoServer()), frame));
        frame.getCliente().inicializar();
        String respuesta = frame.getCliente().peticion(String.valueOf(Cliente.ERES_ROOT));
        if(!respuesta.equals("00")){
            frame.cambiarAConectado();
            addConexionReciente(conexion_texto_ip.getText()+":"+conexion_texto_puerto.getText());
            System.out.println(respuesta);
            frame.setRoot(Boolean.getBoolean(respuesta));
        }    
    }//GEN-LAST:event_conexion_boton_conectarActionPerformed

    private void conexion_texto_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexion_texto_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conexion_texto_ipActionPerformed

    private void conexion_boton_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexion_boton_apagarActionPerformed
        // TODO add your handling code here:
        frame.getCliente().peticion(Character.toString(Cliente.APAGAR));
        frame.cambiarADesconectado();
    }//GEN-LAST:event_conexion_boton_apagarActionPerformed

    private void conexion_texto_puertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexion_texto_puertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conexion_texto_puertoActionPerformed

    private void conexion_texto_ipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conexion_texto_ipKeyPressed
        // TODO add your handling code here:
        if (java.awt.event.KeyEvent.VK_ENTER == evt.getKeyCode()&&!frame.isConnected()){
            conexion_boton_conectarActionPerformed(null);
        }
        if (java.awt.event.KeyEvent.VK_TAB == evt.getKeyCode()&&!frame.isConnected()){
            conexion_texto_puerto.requestFocus();
        }
    }//GEN-LAST:event_conexion_texto_ipKeyPressed

    private void conexion_texto_puertoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conexion_texto_puertoKeyPressed
        // TODO add your handling code here:
        if (java.awt.event.KeyEvent.VK_ENTER == evt.getKeyCode()&&!frame.isConnected()){
            conexion_boton_conectarActionPerformed(null);
        }
    }//GEN-LAST:event_conexion_texto_puertoKeyPressed

    private void conexion_texto_ipFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conexion_texto_ipFocusGained
        // TODO add your handling code here:
        conexion_texto_ip.setText("");
    }//GEN-LAST:event_conexion_texto_ipFocusGained

    private void conexion_texto_puertoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conexion_texto_puertoFocusGained
        // TODO add your handling code here:
        conexion_texto_puerto.setText("");
    }//GEN-LAST:event_conexion_texto_puertoFocusGained

    private void conexion_boton_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexion_boton_desconectarActionPerformed
        // TODO add your handling code here:
        frame.cambiarADesconectado();
    }//GEN-LAST:event_conexion_boton_desconectarActionPerformed

    private void conexion_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexion_actualizarActionPerformed
        // TODO add your handling code here:
        actualizarConexion();
    }//GEN-LAST:event_conexion_actualizarActionPerformed

    public void actualizarConexion(){
        
        conexion_texto_ip.setText("10.0.1.1");
        conexion_texto_puerto.setText("4040");
        for (String conexionesReciente : conexionesRecientes) {
            conexion_textPanel_ippuerto.setText(
                conexion_textPanel_ippuerto.getText() + 
                conexionesReciente + "\n");
        }
        conexion_textPanel_ippuerto.repaint();
      
    }
    
    
    private void leerConexionesRecientes() throws FileNotFoundException, IOException{
        String cadena;
        FileReader f = new FileReader(CONEXIONESRECIENTES);
        BufferedReader b = new BufferedReader(f);
        while((cadena = b.readLine())!=null) {
            if(cadena.contains(":")){
                conexionesRecientes.add(0, cadena);
            }
            else{
                conexionesRecientes.clear();
                return;
            }
        }
        b.close();
    }
    
    public void guardarConexionesRecientes() throws IOException{
        FileWriter f = new FileWriter(CONEXIONESRECIENTES);
        for (String linea : conexionesRecientes) {
                f.write(linea + "\n");
        }
        f.close();
    }
    
    public void addConexionReciente(String r){
        conexionesRecientes.add(0, r);
        if(conexionesRecientes.size() > 10) conexionesRecientes.remove(10);
    }

    
    public javax.swing.JButton getConexion_boton_conectar(){
        return conexion_boton_conectar;
    }
    
    public javax.swing.JButton getConexion_boton_apagar(){
        return conexion_boton_apagar;
    }
    public javax.swing.JButton getConexion_boton_desconectar(){
        return conexion_boton_desconectar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conexion_actualizar;
    private javax.swing.JButton conexion_boton_apagar;
    private javax.swing.JButton conexion_boton_conectar;
    private javax.swing.JButton conexion_boton_desconectar;
    private javax.swing.JTextArea conexion_textPanel_ippuerto;
    private javax.swing.JTextField conexion_texto_ip;
    private javax.swing.JTextField conexion_texto_puerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
