/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import lineasListas.LineaEnrutamiento;
import cliente.Cliente;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import misc.IP;

/**
 *
 * @author raul
 */
public class Enrutamiento extends javax.swing.JPanel {

    private BienvenidaFrame frame;
    private String enrutamiento;
    
    /**
     * Creates new form Enrutamiento
     */
    public Enrutamiento(BienvenidaFrame frame) {
        this.frame = frame;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enrut_jscroll = new javax.swing.JScrollPane();
        enrut_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        enrut_text_destino = new javax.swing.JTextField();
        enrut_text_pasarela = new javax.swing.JTextField();
        enrut_text_genmask = new javax.swing.JTextField();
        enrut_combo_interfaz = new javax.swing.JComboBox<>();
        enrut_boton_anadir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        destino = new javax.swing.JLabel();
        pasarela = new javax.swing.JLabel();
        genmask = new javax.swing.JLabel();
        genmask2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        destino1 = new javax.swing.JLabel();
        pasarela1 = new javax.swing.JLabel();
        genmask1 = new javax.swing.JLabel();
        indic = new javax.swing.JLabel();
        metric = new javax.swing.JLabel();
        ref = new javax.swing.JLabel();
        uso = new javax.swing.JLabel();
        interfaz1 = new javax.swing.JLabel();
        enrut_actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enrut_jscroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        enrut_panel.setBackground(new java.awt.Color(254, 254, 254));
        enrut_panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        enrut_panel.setPreferredSize(new java.awt.Dimension(100, 300));
        enrut_panel.setLayout(new javax.swing.BoxLayout(enrut_panel, javax.swing.BoxLayout.Y_AXIS));
        enrut_jscroll.setViewportView(enrut_panel);

        add(enrut_jscroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 694, 380));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 45));
        jPanel3.setMinimumSize(new java.awt.Dimension(469, 45));
        jPanel3.setPreferredSize(new java.awt.Dimension(692, 45));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        enrut_text_destino.setText("0.0.0.0");
        enrut_text_destino.setPreferredSize(new java.awt.Dimension(135, 34));
        enrut_text_destino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enrut_text_destinoFocusGained(evt);
            }
        });
        enrut_text_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrut_text_destinoActionPerformed(evt);
            }
        });
        jPanel3.add(enrut_text_destino);

        enrut_text_pasarela.setText("0.0.0.0");
        enrut_text_pasarela.setPreferredSize(new java.awt.Dimension(135, 34));
        enrut_text_pasarela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enrut_text_pasarelaFocusGained(evt);
            }
        });
        jPanel3.add(enrut_text_pasarela);

        enrut_text_genmask.setText("255.255.255.0");
        enrut_text_genmask.setPreferredSize(new java.awt.Dimension(135, 34));
        enrut_text_genmask.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enrut_text_genmaskFocusGained(evt);
            }
        });
        enrut_text_genmask.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enrut_text_genmaskKeyPressed(evt);
            }
        });
        jPanel3.add(enrut_text_genmask);

        enrut_combo_interfaz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "blablabla" }));
        enrut_combo_interfaz.setToolTipText("Interfaz servidor");
        enrut_combo_interfaz.setMaximumSize(new java.awt.Dimension(120, 32767));
        enrut_combo_interfaz.setMinimumSize(new java.awt.Dimension(120, 34));
        enrut_combo_interfaz.setPreferredSize(new java.awt.Dimension(120, 34));
        jPanel3.add(enrut_combo_interfaz);

        enrut_boton_anadir.setText("Añadir");
        enrut_boton_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrut_boton_anadirActionPerformed(evt);
            }
        });
        jPanel3.add(enrut_boton_anadir);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 45));
        jPanel2.setMinimumSize(new java.awt.Dimension(469, 45));
        jPanel2.setPreferredSize(new java.awt.Dimension(692, 45));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        destino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destino.setText("Destino");
        destino.setPreferredSize(new java.awt.Dimension(135, 18));
        jPanel2.add(destino);

        pasarela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pasarela.setText("Pasarela");
        pasarela.setPreferredSize(new java.awt.Dimension(135, 18));
        jPanel2.add(pasarela);

        genmask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genmask.setText("Genmask");
        genmask.setPreferredSize(new java.awt.Dimension(135, 18));
        jPanel2.add(genmask);

        genmask2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genmask2.setText("Interfaz");
        genmask2.setPreferredSize(new java.awt.Dimension(135, 18));
        jPanel2.add(genmask2);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 4545));
        jPanel1.setMinimumSize(new java.awt.Dimension(469, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(694, 30));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        destino1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destino1.setText("DESTINO");
        destino1.setToolTipText("Destino");
        destino1.setPreferredSize(new java.awt.Dimension(95, 18));
        jPanel1.add(destino1);

        pasarela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pasarela1.setText("PASARELA");
        pasarela1.setToolTipText("Gateway");
        pasarela1.setPreferredSize(new java.awt.Dimension(95, 18));
        jPanel1.add(pasarela1);

        genmask1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genmask1.setText("GENMASK");
        genmask1.setToolTipText("Máscara de red");
        genmask1.setPreferredSize(new java.awt.Dimension(95, 18));
        jPanel1.add(genmask1);

        indic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indic.setText("INDIC");
        indic.setToolTipText("Flags");
        indic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        indic.setPreferredSize(new java.awt.Dimension(50, 18));
        indic.setRequestFocusEnabled(false);
        jPanel1.add(indic);

        metric.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        metric.setText("METRIC");
        metric.setToolTipText("Métrica");
        metric.setPreferredSize(new java.awt.Dimension(55, 18));
        jPanel1.add(metric);

        ref.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ref.setText("REF");
        ref.setToolTipText("Referencia");
        ref.setPreferredSize(new java.awt.Dimension(40, 18));
        jPanel1.add(ref);

        uso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uso.setText("USO");
        uso.setToolTipText("Uso");
        uso.setMaximumSize(new java.awt.Dimension(45, 18));
        uso.setPreferredSize(new java.awt.Dimension(40, 18));
        jPanel1.add(uso);

        interfaz1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        interfaz1.setText("INTERFAZ");
        interfaz1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        interfaz1.setMaximumSize(new java.awt.Dimension(70, 18));
        interfaz1.setMinimumSize(new java.awt.Dimension(10, 18));
        interfaz1.setPreferredSize(new java.awt.Dimension(70, 18));
        interfaz1.setRequestFocusEnabled(false);
        jPanel1.add(interfaz1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        enrut_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_autorenew_black_24dp.png"))); // NOI18N
        enrut_actualizar.setToolTipText("Refrescar");
        enrut_actualizar.setPreferredSize(new java.awt.Dimension(36, 36));
        enrut_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrut_actualizarActionPerformed(evt);
            }
        });
        add(enrut_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 34)); // NOI18N
        jLabel1.setText("ENRUTAMIENTO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void enrut_boton_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrut_boton_anadirActionPerformed
        // TODO add your handling code here:
        frame.getCliente().peticion(Cliente.ANADE_IP + "route add -net " + enrut_text_destino.getText()
            + " netmask " + enrut_text_genmask.getText()
            + " gw " + enrut_text_pasarela.getText()
            + " dev " + (String)enrut_combo_interfaz.getSelectedItem());
        actualizarEnrutamiento();
    }//GEN-LAST:event_enrut_boton_anadirActionPerformed

    private void enrut_text_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrut_text_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrut_text_destinoActionPerformed

    private void enrut_text_destinoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enrut_text_destinoFocusGained
        // TODO add your handling code here:
        enrut_text_destino.setText("");
    }//GEN-LAST:event_enrut_text_destinoFocusGained

    private void enrut_text_pasarelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enrut_text_pasarelaFocusGained
        // TODO add your handling code here:
        enrut_text_pasarela.setText("");
    }//GEN-LAST:event_enrut_text_pasarelaFocusGained

    private void enrut_text_genmaskFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enrut_text_genmaskFocusGained
        // TODO add your handling code here:
        enrut_text_genmask.setText("");
    }//GEN-LAST:event_enrut_text_genmaskFocusGained

    private void enrut_text_genmaskKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrut_text_genmaskKeyPressed
        // TODO add your handling code here:
        if (java.awt.event.KeyEvent.VK_ENTER == evt.getKeyCode()&&!frame.isConnected()){
            enrut_boton_anadirActionPerformed(null);
        }
    }//GEN-LAST:event_enrut_text_genmaskKeyPressed

    private void enrut_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrut_actualizarActionPerformed
        // TODO add your handling code here:
        actualizarEnrutamiento();
    }//GEN-LAST:event_enrut_actualizarActionPerformed

    public void actualizarEnrutamiento(){
        this.enrutamiento = frame.getCliente().peticion(Character.toString(Cliente.DAME_ENRUTAMIENTO)); 
        frame.setRoot(Boolean.valueOf(frame.getCliente().peticion(String.valueOf(Cliente.ERES_ROOT))));
        
        
        enrut_panel.removeAll();
        Scanner scanner = new Scanner(enrutamiento);
        enrut_boton_anadir.setEnabled(frame.isRoot());
        while (scanner.hasNextLine())enrut_panel.add(new LineaEnrutamiento(scanner.nextLine(),frame, frame.isRoot()));
        scanner.close();
        enrut_panel.revalidate();
        enrut_panel.repaint();
        
        String s = frame.getCliente().peticion(String.valueOf(Cliente.DAME_IP));
        if (s.equals("00")){
            frame.cambiarADesconectado();
            return;
        }
        ArrayList<IP> aip = frame.getPConfiguracion().decodeIPS(s);
        ArrayList<String> list = new ArrayList<String>();
        for (IP i : aip) {
                list.add(i.getName());
        }
        enrut_combo_interfaz.setModel(new DefaultComboBoxModel<String>((String[])list.toArray(new String[list.size()])));
        enrut_combo_interfaz.setSelectedItem(list.get(0));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destino;
    private javax.swing.JLabel destino1;
    private javax.swing.JButton enrut_actualizar;
    private javax.swing.JButton enrut_boton_anadir;
    private javax.swing.JComboBox<String> enrut_combo_interfaz;
    private javax.swing.JScrollPane enrut_jscroll;
    private javax.swing.JPanel enrut_panel;
    private javax.swing.JTextField enrut_text_destino;
    private javax.swing.JTextField enrut_text_genmask;
    private javax.swing.JTextField enrut_text_pasarela;
    private javax.swing.JLabel genmask;
    private javax.swing.JLabel genmask1;
    private javax.swing.JLabel genmask2;
    private javax.swing.JLabel indic;
    private javax.swing.JLabel interfaz1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel metric;
    private javax.swing.JLabel pasarela;
    private javax.swing.JLabel pasarela1;
    private javax.swing.JLabel ref;
    private javax.swing.JLabel uso;
    // End of variables declaration//GEN-END:variables
}
