/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc;

/**
 *
 * @author raul
 */
public class ArgumentosPop_up extends javax.swing.JPanel {

    /**
     * Creates new form ArgumentosPop_up
     */
    public ArgumentosPop_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        argspopup_editable_argumentos = new javax.swing.JTextField();
        argspopup_texto_proceso = new javax.swing.JLabel();

        argspopup_editable_argumentos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        argspopup_editable_argumentos.setText("argumentos");
        argspopup_editable_argumentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                argspopup_editable_argumentosFocusGained(evt);
            }
        });
        argspopup_editable_argumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                argspopup_editable_argumentosActionPerformed(evt);
            }
        });

        argspopup_texto_proceso.setText("proceso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(argspopup_texto_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(argspopup_editable_argumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(argspopup_editable_argumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(argspopup_texto_proceso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void argspopup_editable_argumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_argspopup_editable_argumentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_argspopup_editable_argumentosActionPerformed

    private void argspopup_editable_argumentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_argspopup_editable_argumentosFocusGained
        // TODO add your handling code here:
        argspopup_editable_argumentos.setText("");
    }//GEN-LAST:event_argspopup_editable_argumentosFocusGained

    public void setProceso(String proceso){
        argspopup_texto_proceso.setText(proceso);
    }
    
    public String getProceso(){
        return argspopup_texto_proceso.getText();
    }
    
    public String getArgumentos(){
        return argspopup_editable_argumentos.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField argspopup_editable_argumentos;
    private javax.swing.JLabel argspopup_texto_proceso;
    // End of variables declaration//GEN-END:variables
}
